version: '3.1'

services: 
  ui:
    build: .
    ports: 
      - 8080:8080
    environment:
      NODE_ENV: 'development'
      VUE_APP_API_URL: 'http://localhost:3000'
      VUE_APP_JWT_TOKEN_KEY: 'auth_token'

